import { dpToSp } from "@/utils/dpToSp";

export const typography = {
  h1: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(38),
    lineHeight: 46,
    letterSpacing: -0.3,
  },
  h2: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(30),
    lineHeight: 40,
    letterSpacing: -0.5,
  },
  h3: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(26),
    lineHeight: 32,
    letterSpacing: 0,
  },
  h4: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(24),
    lineHeight: 28,
    letterSpacing: 0,
  },
  h4Medium: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(24),
    lineHeight: 28,
    letterSpacing: 0,
  },
  h5: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(20),
    lineHeight: 26,
    letterSpacing: 0,
  },
  h5Medium: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(20),
    lineHeight: 26,
    letterSpacing: 0,
  },
  h6: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(18),
    lineHeight: 24,
    letterSpacing: 0,
  },
  h6Medium: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(18),
    lineHeight: 24,
    letterSpacing: 0,
  },
  subtitle1: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(16),
    lineHeight: 22,
    letterSpacing: 0,
  },
  subtitle2: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(15),
    lineHeight: 24,
    letterSpacing: 0,
  },
  inputText: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(15),
    lineHeight: 18,
    letterSpacing: 0.15,
  },
  body: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(18),
    lineHeight: 24,
    letterSpacing: 0,
  },
  body2: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(14),
    lineHeight: 20,
    letterSpacing: 0,
  },
  buttonLink: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(15),
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodyMedium: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(14),
    lineHeight: 20,
    letterSpacing: 0,
  },
  caption: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(13),
    lineHeight: 16,
    letterSpacing: 0,
  },
  inputLabel: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(13),
    lineHeight: 16,
    letterSpacing: 0.15,
  },
  helperText: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(12),
    lineHeight: 14,
    letterSpacing: 0.4,
  },
  helperTextMedium: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(12),
    lineHeight: 14,
    letterSpacing: 0.4,
  },
  buttonLarge: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(15),
    lineHeight: 20,
    letterSpacing: 0.7,
  },
  buttonMedium: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(14),
    lineHeight: 20,
    letterSpacing: 0.7,
  },
  buttonSmall: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(13),
    lineHeight: 20,
    letterSpacing: 0.7,
  },
  textSmall: {
    fontFamily: "EtelkaText",
    fontSize: dpToSp(10),
    lineHeight: 11.25,
  },
  textMediumSmall: {
    fontFamily: "EtelkaMedium",
    fontSize: dpToSp(10),
    lineHeight: 16,
    letterSpacing: 1.5,
  },
};
