export const typography = {
  h1: {
    fontFamily: "EtelkaMedium",
    fontSize: 38,
    lineHeight: 46,
    letterSpacing: -0.3,
  },
  h2: {
    fontFamily: "EtelkaText",
    fontSize: 30,
    lineHeight: 40,
    letterSpacing: -0.5,
  },
  h3: {
    fontFamily: "EtelkaMedium",
    fontSize: 26,
    lineHeight: 32,
    letterSpacing: 0,
  },
  h4: {
    fontFamily: "EtelkaText",
    fontSize: 24,
    lineHeight: 28,
    letterSpacing: 0,
  },
  h5: {
    fontFamily: "EtelkaText",
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: 0,
  },
  h5Medium: {
    fontFamily: "EtelkaMedium",
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: 0,
  },
  h6: {
    fontFamily: "EtelkaText",
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
  },
  h6Medium: {
    fontFamily: "EtelkaMedium",
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
  },
  subtitle1: {
    fontFamily: "EtelkaText",
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0,
  },
  subtitle2: {
    fontFamily: "EtelkaText",
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0,
  },
  body: {
    fontFamily: "EtelkaText",
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
  },
  body2: {
    fontFamily: "EtelkaText",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  bodyMedium: {
    fontFamily: "EtelkaMedium",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  caption: {
    fontFamily: "EtelkaText",
    fontSize: 13,
    lineHeight: 16,
    letterSpacing: 0,
  },
  inputText: {
    fontFamily: "EtelkaText",
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: 0.15,
  },
  inputLabel: {
    fontFamily: "EtelkaText",
    fontSize: 13,
    lineHeight: 16,
    letterSpacing: 0.15,
  },
  helperText: {
    fontFamily: "EtelkaText",
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.4,
  },
  helperTextMedium: {
    fontFamily: "EtelkaMedium",
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.4,
  },
  buttonLarge: {
    fontFamily: "EtelkaMedium",
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: 0.7,
  },
  buttonMedium: {
    fontFamily: "EtelkaMedium",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.7,
  },
  buttonSmall: {
    fontFamily: "EtelkaMedium",
    fontSize: 13,
    lineHeight: 20,
    letterSpacing: 0.7,
  },
  textSmall: {
    fontFamily: "EtelkaText",
    fontSize: 10,
    lineHeight: 11.25,
  },
  textMediumSmall: {
    fontFamily: "EtelkaMedium",
    fontSize: 10,
    lineHeight: 16,
    letterSpacing: 1.5,
  },
};
